server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.116.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    pubKeyPath: C:\Users\Lenovo\Desktop\master\spring_zg2_demo\id_rsa.pub
    cookieName: LY_TOKEN
