server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.116.128:9300
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.116.128
    username: leyou
    password: 123456
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5